APP_CONFIG = {
    'DATA_S3_BUCKET': 'efmldevelopment',
    'DATA_S3_ACCESS': 'AKIAIXXXXXXXXXXXX',
    'DATA_S3_SECRET': 'XXXXXXXXXXXXXXXXXXXXXXX',
    'DEV_ENV' : 'DEV-ITHACA-APPROVAL-ODDS-MODEL-INSTANCE'
}
