from config import APP_CONFIG

METADATA_FILE = "metadata.txt"
CARD_VARS_FILE = "card_variables.csv"

DATA_DIR = '/opt/ml/data/'
LATEST_METADATA_FILE_LOCAL = DATA_DIR + METADATA_FILE + ".latest"
METADATA_FILE_LOCAL = DATA_DIR + METADATA_FILE
CARD_VARS_FILE_LOCAL = DATA_DIR + CARD_VARS_FILE