from config import APP_CONFIG

METADATA_FILE = "metadata.txt"
CARD_COMM_FILE = "card_commissions.csv"
CARD_VARS_FILE = "card_variables.csv"
CARD_PAGE_FILE = "pagecard_mapping.csv"

DATA_DIR = '/opt/ml/data/'
LATEST_METADATA_FILE_LOCAL = DATA_DIR + METADATA_FILE + ".latest"
METADATA_FILE_LOCAL = DATA_DIR + METADATA_FILE
CARD_COMM_FILE_LOCAL = DATA_DIR + CARD_COMM_FILE
CARD_VARS_FILE_LOCAL = DATA_DIR + CARD_VARS_FILE
CARD_PAGE_FILE_LOCAL = DATA_DIR + CARD_PAGE_FILE